services:
  mopay:
    image: ghcr.io/pbuzdygan/rakit:latest
    container_name: rakit
    restart: unless-stopped
    network_mode: host
# Environment variables
    environment:
      - PORT=8011 #in network_mode host You can set different than default port
      - DB_FILE=/data/rakit_db.sqlite
      - APP_PIN=123456 #PIN 4-8 digits
      - NODE_ENV=production
      - APP_ENC_KEY=YOUR_ENC_KEY_HERE
# Persistent data (if backend writes anything to /data)
    volumes:
      - ./data:/data
#    ports:
#      - "8011:8011"
